project_id = "nswjmgrqgvgxlchefeca"

[functions.check-connect-status]
verify_jwt = false

[functions.check-identity-verification]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.create-identity-verification]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false
